# -*- coding: utf-8 -*-
{
    "name": "Nexus Advanced Financial Engine / محرك المحاسبة المالية المتقدمة",
    "version": "18.0.1.0.0",
    "category": "Nexus/Accounting",
    "summary": "Nexus Dual-Ledger Financial Suite — Chart of Accounts, Cost Centers, Journal Entries, General Ledger, Payments, Budgets, and Fiscal Management.",
    "author": "Nexus Enterprise Architecture",
    "website": "https://nexus-engine.app",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "account",
        "project",
        "nexus_base_security",
        "ai_enterprise_copilot",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "data/account_types.xml",
        "views/nexus_account_views.xml",
        "views/nexus_cost_center_views.xml",
        "views/nexus_fiscal_year_views.xml",
        "views/nexus_party_account_views.xml",
        "views/nexus_journal_entry_views.xml",
        "views/nexus_gl_entry_views.xml",
        "views/nexus_payment_entry_views.xml",
        "views/nexus_budget_views.xml",
        "views/nexus_accounting_menus.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
