"""Nexus Enterprise Engine - Internal Validation Loop.

This script checks that file references, Python imports, and Flutter
references are consistent. Drift `.g.dart` files are expected to be
generated by `dart run build_runner build`; missing generated files are
reported but not treated as broken source references.
"""
import ast
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parent


def log(status: str, message: str) -> None:
    print(f"[{status:7}] {message}")


def find_files(base: Path, pattern: str) -> Iterable[Path]:
    return base.rglob(pattern)


def read_python_imports(file: Path) -> list[str]:
    try:
        tree = ast.parse(file.read_text(encoding="utf-8"), filename=str(file))
    except SyntaxError as exc:
        log("ERROR", f"{file}: syntax error - {exc}")
        return []

    imports: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                imports.append(alias.name or "")
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                imports.append(node.module)
    return imports


def check_python_imports() -> int:
    errors = 0
    py_files = list(find_files(ROOT, "*.py"))

    # Build a set of local package roots.
    local_packages = {
        p.name
        for p in ROOT.iterdir()
        if p.is_dir() and (p / "__init__.py").exists()
    }
    local_packages.add("odoo")

    for file in py_files:
        if file.name.endswith(".g.py"):
            continue
        for module in read_python_imports(file):
            if not module:
                continue
            top = module.split(".")[0]
            if top in ("odoo", "logging", "datetime", "json", "re", "tempfile"):
                # Standard / Odoo runtime modules; skip runtime checks.
                continue
            if top in local_packages:
                # Resolve local module.
                parts = module.split(".")
                target = ROOT / parts[0]
                for part in parts[1:]:
                    target = target / part
                if not (target.with_suffix(".py").exists() or (target / "__init__.py").exists()):
                    log("ERROR", f"{file}: unresolved local module '{module}'")
                    errors += 1
    return errors


def check_flutter_references() -> int:
    errors = 0
    dart_files = list(find_files(ROOT / "flutter_pos" / "lib", "*.dart"))
    lib_root = ROOT / "flutter_pos" / "lib"

    import_re = re.compile(r"^import\s+['\"]([^'\"]+)['\"]")
    part_re = re.compile(r"^part\s+['\"]([^'\"]+)['\"]")

    for file in dart_files:
        for line_num, line in enumerate(file.read_text(encoding="utf-8").splitlines(), 1):
            m = import_re.match(line)
            if m:
                target = m.group(1)
                if target.startswith("package:flutter_pos/"):
                    rel = target.replace("package:flutter_pos/", "")
                    target_path = lib_root / rel
                    if not target_path.exists():
                        log("ERROR", f"{file}:{line_num}: missing '{target}'")
                        errors += 1
                continue

            m = part_re.match(line)
            if m:
                part_file = m.group(1)
                part_path = file.parent / part_file
                if not part_path.exists():
                    if part_file.endswith(".g.dart"):
                        log("WARN", f"{file}:{line_num}: missing generated file '{part_file}' (run `make build-flutter`)")
                    else:
                        log("ERROR", f"{file}:{line_num}: missing part file '{part_file}'")
                        errors += 1
    return errors


def check_odoo_manifests() -> int:
    errors = 0
    manifests = list(find_files(ROOT / "odoo-backend" / "custom_addons", "__manifest__.py"))
    for manifest in manifests:
        try:
            data = ast.literal_eval(manifest.read_text(encoding="utf-8"))
        except (SyntaxError, ValueError) as exc:
            log("ERROR", f"{manifest}: invalid manifest - {exc}")
            errors += 1
            continue

        for file in data.get("data", []):
            target = manifest.parent / file
            if not target.exists():
                log("ERROR", f"{manifest}: missing data file '{file}'")
                errors += 1
    return errors


def check_docker_compose() -> int:
    errors = 0
    compose_file = ROOT / "docker-compose.yml"
    if not compose_file.exists():
        log("ERROR", "docker-compose.yml is missing")
        errors += 1
    else:
        try:
            import yaml

            with compose_file.open("r", encoding="utf-8") as f:
                _ = yaml.safe_load(f)
            log("OK", "docker-compose.yml parsed")
        except ImportError:
            log("WARN", "PyYAML not installed; cannot validate docker-compose.yml syntax")
        except Exception as exc:
            log("ERROR", f"docker-compose.yml: {exc}")
            errors += 1
    return errors


def check_pubspec_dependencies() -> int:
    errors = 0
    pubspec = ROOT / "flutter_pos" / "pubspec.yaml"
    if not pubspec.exists():
        log("ERROR", "flutter_pos/pubspec.yaml is missing")
        return 1
    try:
        import yaml

        with pubspec.open("r", encoding="utf-8") as f:
            doc = yaml.safe_load(f)
        deps = set((doc.get("dependencies") or {}).keys())
        required = {
            "drift",
            "dio",
            "flutter_bloc",
            "crypto",
            "esc_pos_printer",
            "stripe_terminal",
        }
        missing = required - deps
        if missing:
            log("ERROR", f"pubspec.yaml missing required dependencies: {missing}")
            errors += 1
        else:
            log("OK", "pubspec.yaml contains required dependencies")
    except ImportError:
        log("WARN", "PyYAML not installed; cannot validate pubspec.yaml")
    except Exception as exc:
        log("ERROR", f"pubspec.yaml: {exc}")
        errors += 1
    return errors


def run_python_lint() -> int:
    errors = 0
    for file in find_files(ROOT / "odoo-backend" / "custom_addons", "*.py"):
        try:
            ast.parse(file.read_text(encoding="utf-8"))
        except SyntaxError as exc:
            log("ERROR", f"{file}: Python syntax error - {exc}")
            errors += 1
    for file in find_files(ROOT / "ai_services", "*.py"):
        try:
            ast.parse(file.read_text(encoding="utf-8"))
        except SyntaxError as exc:
            log("ERROR", f"{file}: Python syntax error - {exc}")
            errors += 1
    return errors


def attempt_flutter_build() -> int:
    """If Flutter is installed, run pub get and build_runner."""
    try:
        subprocess.run(["flutter", "--version"], check=True, capture_output=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        log("WARN", "Flutter not installed; skipping Flutter build validation")
        return 0

    log("INFO", "Flutter detected; attempting `flutter pub get` and build_runner")
    try:
        subprocess.run(
            ["flutter", "pub", "get"],
            cwd=ROOT / "flutter_pos",
            check=True,
        )
        subprocess.run(
            ["dart", "run", "build_runner", "build", "--delete-conflicting-outputs"],
            cwd=ROOT / "flutter_pos",
            check=True,
        )
        return 0
    except subprocess.CalledProcessError as exc:
        log("ERROR", f"Flutter build failed: {exc}")
        return 1


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Nexus validation loop")
    parser.add_argument(
        "--build-flutter",
        action="store_true",
        help="Run `flutter pub get` and `build_runner build` if Flutter is installed.",
    )
    args = parser.parse_args()

    log("INFO", "Starting Nexus validation loop")
    total = 0
    total += check_python_imports()
    total += check_flutter_references()
    total += check_odoo_manifests()
    total += check_docker_compose()
    total += check_pubspec_dependencies()
    total += run_python_lint()

    if args.build_flutter:
        total += attempt_flutter_build()

    if total == 0:
        log("PASS", "All structural validation checks passed")
        return 0
    else:
        log("FAIL", f"Validation found {total} issue(s)")
        return 1


if __name__ == "__main__":
    sys.exit(main())
