name: flutter_pos
version: 1.0.0+1
publish_to: "none"

description: Nexus offline-first Flutter POS for retail, fuel, hospitality and US markets.

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.20
  dio: ^5.4.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  collection: ^1.18.0
  crypto: ^3.0.3
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  stripe_terminal: ^1.3.0
  flutter_stripe: ^10.0.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  logger: ^2.0.2
  uuid: ^4.3.3
  path: ^1.8.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true