{
    "name": "Nexus SaaS Tenant / مستأجرو Nexus",
    "version": "18.0.1.0.0",
    "category": "Nexus/SaaS",
    "summary": "Multi-tenant foundation for Nexus ERP: tenant isolation, plans, quotas, and self-service provisioning.",
    "author": "Nexus Engine",
    "website": "https://nexus-engine.app",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "web",
        "account",
        "nexus_base_security",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/tenant_rules.xml",
        "data/cron.xml",
        "data/demo_plans.xml",
        "views/plan_views.xml",
        "views/tenant_views.xml",
        "views/subscription_views.xml",
        "views/usage_views.xml",
        "views/res_config_settings_views.xml",
        "views/saas_menus.xml",
    ],
    "post_init_hook": "_post_init_hook",
    "installable": True,
    "application": True,
    "auto_install": False,
}
