{
    "name": "AI Enterprise Copilot",
    "version": "18.0.1.0.0",
    "category": "Productivity",
    "summary": "AI governance and proactive support engine for the Nexus hybrid architecture.",
    "author": "Nexus Engine",
    "website": "https://nexus-engine.app",
    "license": "LGPL-3",
    "depends": ["base", "account", "mail", "stock", "hr", "mrp", "point_of_sale", "odoo_erpnext_hybrid_sync", "nexus_base_security"],
    "data": [
        "security/ir.model.access.csv",
        "data/cron.xml",
        "views/settings_view.xml",
        "views/dashboard_view.xml",
        "views/milestone_views.xml",
        "views/setup_journey_views.xml",
        "views/accounting_menus.xml",
        "views/onboarding_wizard_views.xml",
        "views/document_hunter_wizard_views.xml",
        "views/ai_developer_staff_views.xml",
        "views/universal_migrator_views.xml",
        "views/finance_report_views.xml",
        "views/finance_dashboard_views.xml",
        "views/finance_dashboard_main.xml",
        "views/bom_advisor_views.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
